### ISSUE TITLE
Iterate misses elements

### ISSUE THREAD

**Issue by MondayHopscotch** [Aidan63/ecs#14]
It appears that trying to remove components from within `iterate(...)` can stop early. 

I have a situation where I was seeing the second half of a family not be hit. I have a cleanup system that just makes sure all entities have a specific component removed at the end of the phase, like this:
```
package system;

import ecs.System;

import comp.FrameCollisions;

class CollisionCleanupSystem extends System {
	@:fastFamily var collisionsFamily : {
		col: comp.FrameCollisions
	}

	override function update(_dt:Float) {
		super.update(_dt);
		iterate(collisionsFamily, (entity) -> {
			universe.removeComponents(entity, FrameCollisions);
		});
	}
}
```

However, it misses entities. When I refactor it to pull out the list of entities, then iterate over them separately, like below, it works as expected.

```
package system;

import ecs.Entity;
import ecs.System;

import comp.FrameCollisions;

class CollisionCleanupSystem extends System {
	@:fastFamily var collisionsFamily : {
		col: comp.FrameCollisions
	}

	override function update(_dt:Float) {
		super.update(_dt);

		var entities:Array<Entity> = [];
		iterate(collisionsFamily, entity -> {
			trace('entity ${entity}');
			entities.push(entity);
		});

		for (e in entities) {
			universe.removeComponents(e, FrameCollisions);
		}
	}
}
```

**Comment by Aidan63** [comment]
Yes, unfortunately iterate is not safe when it comes to adding / deleting / generally changing entities. It could be changed to be safe for the current entity (like your example), but still wouldn't be safe for other entities which might be in the currently iterated family.

I'll look into updating it so stuff like your example would be allowed, and maybe there needs to be some sort of "scratch space" convenience classes for other cases.

**Comment by MondayHopscotch** [comment]
I assume the issue is probably with the indices being used under the hood? Now that I've had time to let it soak, the behavior I was seeing definitely appears that it's just an index sort of thing (iterator moving forward as elements are being removed).

My only 'beef' with my workaround is that I have to have a separate list to keep track of the entities. Ideally I wouldnt have to allocate additional data to facilitate removing a component from all entities. (maybe there's a different approach to doing that?)

**Comment by Aidan63** [comment]
yeah, the iterator currently iterates forward across the sparse set of entities. Simply changing it to iterate backwards should allow the use case in your example, but modifying entities other than the current one would still cause issues (maybe nested iterates on the same family as well, but I'm willing to treat that as a bit of an edge case for now).

Instead of trying to support all possible cases I'm thinking a more formalised version of what your workaround might work. e.g.

```haxe
final scratch = universe.scratch.getSpace();

iterate(someFamily, e1 -> {
    iterate(someOtherFamily, e2 -> {
        final someOtherEntity = // some code to get an entity in one of these two families but not the ones currently iterated.
        // instead of immediately operating on it put it in the scratch space for defered operations.
        scratch.push(someOtherEntity);
    });
});

// after our iterates delete all the entities.
// maybe provide an api like removeComponent(SomeComponent) for batch operations?
scratch.deleteAll();
scratch.release();
```

This way we could pool pre-allocated scrach space arrays to avoid allocations.

**Comment by MondayHopscotch** [comment]
Just updated and played around with this. It looks great 👍
