### ISSUE TITLE
TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by Jarrio** [Aidan63/ecs#5]
Was setting up a test project to see if i could isolate something else and i got this guy again. It seems to be consistent on the node target and i can't get interp to maintain the app loop. I have attached the basic project to avoid any accidental misses! 
[ecs-repro.zip](https://github.com/Aidan63/ecs/files/5751549/ecs-repro.zip)
(node launch config is preconfigured)

**Comment by Aidan63** [comment]
This seems to be related to the previous issue, in this case adding `import Logger` to Main.hx solves the issue. I did do some more digging into whats actually causing this and now know why, just need to find a good solution.

I was under the assumption all build macros would be processed before expression macros but that doesn't seem to be the case. I use an expression macro in the universe to create a fixed sized vector to hold all components, but when it types that expression macro it think there are no components so creates a vector of size 0 which causes that undefined (null) error. I'm guessing importing the logger system will mean the build macro gets processed first (which will register its family and components).

**Comment by Aidan63** [comment]
Closing this to track the underlying issue in #6
